diff -dur japa-0.8.4.orig/source/Makefile japa-0.8.4/source/Makefile
--- japa-0.8.4.orig/source/Makefile	2013-07-01 12:07:44.000000000 +0200
+++ japa-0.8.4/source/Makefile	2016-10-15 12:52:20.207337272 +0200
@@ -24,15 +24,14 @@
 LIBDIR = lib$(SUFFIX)
 VERSION = 0.8.4
 CPPFLAGS += -DVERSION=\"$(VERSION)\" -DPREFIX=\"$(PREFIX)\" -I/usr/include/freetype2
-CXXFLAGS += -O2 -Wall -MMD -MP
-CXXFLAGS += -march=native
+CXXFLAGS += -Wall -MMD -MP
 LDFLAGS += -L/usr/X11R6/$(LIBDIR)
 LDLIBS += -lzita-alsa-pcmi -lclthreads -lclxclient -lpthread -lfftw3f -ljack -lasound -lpthread -lXft -lX11 -lrt
 
 
 JAPA_O = analyser.o audio.o gobjects.o japa.o mainwin.o styles.o rngen.o
 japa:	$(JAPA_O)
-	g++ $(LDFLAGS) -o $@ $(JAPA_O) $(LDLIBS)
+	$(CXX) $(LDFLAGS) -o $@ $(JAPA_O) $(LDLIBS)
 
 $(JAPA_O):
 -include $(JAPA_O:%.o=%.d)
