--- japa-0.9.2/source/Makefile.orig	2021-09-27 20:41:34.379853988 +0200
+++ japa-0.9.2/source/Makefile	2021-09-27 20:43:04.616031804 +0200
@@ -23,9 +23,8 @@ BINDIR ?= $(PREFIX)/bin
 
 VERSION = 0.9.2
 CPPFLAGS += -MMD -MP -DVERSION=\"$(VERSION)\" -DPREFIX=\"$(PREFIX)\"
-CPPFLAGS += $(shell pkgconf --cflags freetype2)
-CXXFLAGS += -O2 -Wall
-CXXFLAGS += -march=native
+CPPFLAGS += $(shell pkg-config --cflags xft)
+CXXFLAGS += -Wall
 LDLIBS += -lzita-alsa-pcmi -lclthreads -lclxclient -lasound -lpthread \
 	-lfftw3f -ljack -lXft -lX11 -lrt
 
